### ISSUE TITLE
How to add TenantId during login process?

### ISSUE THREAD

**Issue by mikeandersun** [JSkimming/AspNet.Identity.EntityFramework.Multitenant#11]
I need to add a the tenantId during login and registeration process.
Thanks a lot for your point me to right way.

**Comment by JSkimming** [comment]
@mikeandersun the TenentId is a publicly settable property on the MultitenantUserStore, you need to set that property.

**Comment by JSkimming** [comment]
Closing on the assumption all has been answered, feel free to reopen should further clarification be required.
