### ISSUE TITLE
UserManager.FindByName() - UserManager.FindByEmail()

### ISSUE THREAD

**Issue by wjchristenson2** [JSkimming/AspNet.Identity.EntityFramework.Multitenant#13]
This may be more of a question than an issue, but I ran into an issue where I need to find a user for a given tenant using their username and/or email. It appears the Find methods for the UserManager may not be filtering on the TenantId. Am I missing something? If not, any other way to find a user based on username or email w/ a Tenant filter?

**Comment by JSkimming** [comment]
@wjchristenson2 I've just updated the readme to add a [How to use multi-tenancy](https://github.com/JSkimming/AspNet.Identity.EntityFramework.Multitenant/blob/master/README.md#how-to-use-multi-tenancy) section, does that help in any way?

**Comment by wjchristenson2** [comment]
The documentation snippet you added is helpful. The issue was on my end and you can close the ticket. Explanation below.

I was debugging/flipping between tenants (localhost). I have the same username/email on two tenants. I had a routine which checks for uniqueness of username when managing accounts which used the UserManager.Find methods coupled with the currently logged in userId. I forgot to logout of the old tenant before testing the new resulting in a situation which appeared that the .Find() methods where not using the TenantId. However, the routine was using the userId of the wrong tenant which threw off the dup logic.
