### ISSUE TITLE
Could you please include functionality to utilize the existing functions?

### ISSUE THREAD

**Issue by NJTCS** [JSkimming/AspNet.Identity.EntityFramework.Multitenant#14]
GenerateEmailConfirmationToken
GenerateChangePhoneNumberToken
GeneratePasswordResetToken
GenerateTwoFactorToken
GenerateUserToken

**Comment by JSkimming** [comment]
@NJTCS Those methods all take UserId, which is the unique primary key of a user within the database and is globally unique across tenants.

Presumably the user has already been identified by a means that supports multi-tenancy, e.g. email or username.

Therefore once you have the UserId those methods work as before.
