### ISSUE TITLE
Q: Why TenantId in AspNetUserLogins?

### ISSUE THREAD

**Issue by Peperud** [JSkimming/AspNet.Identity.EntityFramework.Multitenant#25]
The table already has a link to the user which will have an associated TenantId. 
Why have the TenantId in the user logins table then?

**Comment by JSkimming** [comment]
@Peperud I'm not as familiar as I once was with this library, but I think it's because that table uses the identifier from third parties as a unique key, e.g. from Google/Facebook. Therefore, without the TenantId there would be conflicts across tenants.
