### ISSUE TITLE
MultitenantUserStore.FindByEmailAsync doesn't take tenantId into consideration

### ISSUE THREAD

**Issue by kether667** [JSkimming/AspNet.Identity.EntityFramework.Multitenant#5]
TenantId is not taken into consideration when using with RequireUniqueEmail = true on UserValidator

            manager.UserValidator = new UserValidator<ApplicationUser>(manager)
            {
                AllowOnlyAlphanumericUserNames = false,
                RequireUniqueEmail = false
            };

Root cause is that IUserEmailStore doesn't mark FindByEmailAsync as virtual and since MultitenantUserStore extends default UserStore which doesn't know anything about tenantId it cannot work properly.

Solution is to copy&paste UserStore<TUser, TRole, TKey, TUserLogin, TUserRole, TUserClaim> into and modify IUserEmailStore.FindByEmailAsync implementation... 

or make MS mark FindByEmailAsync as virtual

**Comment by rikkreeftenberg** [comment]
Hi James,

I was wondering if you could add the MultitenantUserStore.FindByEmailAsync:

        public override Task<TUser> FindByEmailAsync(string email)
        {
            if (string.IsNullOrWhiteSpace(email))
                throw new ArgumentNullException("email");

            ThrowIfInvalid();

            return Users.Where(u => u.Email == email && u.TenantId.Equals(TenantId)).FirstOrDefaultAsync();
        }


Since the Microsoft ASP.NET Identity Entityframeword version 2.2 is released, you can push the new Multitenant Library to Nuget. 
I'm using the library in a production system and I'm very glad with it!

So thank you for your effort.

Regards,

Rik

**Comment by JSkimming** [comment]
[Release 1.2.0](https://github.com/JSkimming/AspNet.Identity.EntityFramework.Multitenant/releases/tag/v1.2.0) has just been pushed to [NuGet](https://www.nuget.org/packages/AspNet.Identity.EntityFramework.Multitenant/1.2.0)
