### ISSUE TITLE
register with a different tenant code

### ISSUE THREAD

**Issue by shrenicshah** [JSkimming/AspNet.Identity.EntityFramework.Multitenant#9]
Hi James,

Sorry to put this under an "issue" section. I couldnt find a way to contact you. I just needed some directions in knowing how do I register using a different tenant code

Kind Regards

Shrenik

**Comment by JSkimming** [comment]
@shrenicshah The solution comes with two example sites showing how to use the __MultitenantUserStore__.

You need to set the `TenantId`. In the [example](https://github.com/JSkimming/AspNet.Identity.EntityFramework.Multitenant/blob/v1.2.0/src/Examples/VanillaImplementation/Controllers/AccountController.cs#L19) it's hard coded, but you need to determine how you distinguish tenants and set it on the __MultitenantUserStore__ to allow it to work.
